### ISSUE TITLE
deploy smart contract upgrade

### ISSUE THREAD

**Issue by lukemarsden** [CoopHive/coophive#11]
This PR https://github.com/CoopHive/coophive/pull/8 has a change to add a new event in the storage contract.

This issue is for building the tooling necessary to upgrade the storage contract without changing the controller contract

- [x] We need a new stack command that runs a new hardhat script that deploys an upgraded storage contract then calls setStorageAddress on the controller
- [x] Then we need to test the upgrade carefully
- [x] Then apply it to production

**Comment by polus-arcticus** [comment]
@lukemarsden good to be merged, shall i go ahead and redeploy on the ec2 instance? or would you like to test yourself first?

**Comment by lukemarsden** [comment]
Lgtm, please go ahead and merge and deploy!
