### ISSUE TITLE
Figure out what went wrong with post-upgrade deployment and get network redeployed with upgraded smart contracts

### ISSUE THREAD

**Issue by lukemarsden** [CoopHive/coophive#30]
please take 080a3485b3e4e961c80b10350453969fcfc57699 (the version of everything currently deployed) and main@HEAD and figuring out:

a) does main@HEAD still run end-to-end with SDXL (you can use the PiKNiK machine as a Linux dev machine with a GPU for a second, see https://github.com/CoopHive/coophive/blob/main/ARCHITECTURE.md ./stack resource-provider --offer-gpu 1 etc)
b) if it does, we can upgrade production back to main@HEAD - but let's coordinate this
c) if it doesn't, try to figure out which change broke it? was it the new event in the smart contract? or some ABI mismatch? something else?

**Comment by polus-arcticus** [comment]
- [x] main@head sdxl
- [x] production upgrade main@head

Ensure to regenerate go-bindings, than compile the binary on contract changes
- [x] build from source
- [ ] test build from release
