### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by lukemarsden** [CoopHive/coophive#31]
* [x] Simply reducing the noise in the logs would be a good start
* [ ] Adding log levels with something like logrus
* [ ] Adding centralized logging with something like Grafana Cloud

---

From Levi: add robust logging to the entire codebase. 

There are a bunch of log levels to choose from, and I'll leave that up to discussion. Primarily though, there should be two main modes: what is happening (basically INFO), and then if something went wrong, what went wrong (basically DEBUG). 

For an example of "what is happening", clone https://github.com/CoopHive/coophive-simulator, run `test_3.py`, and look at the `local_logs` that are generated. It should be roughly that clean. Timestamps are important here as well. These logs should be neatly formatted for machine readability, e.g. something that we can easily put into an ETL pipeline for data analysis.

For the "what went wrong scenario", the logs should look more like they currently do, but again, neatly formatted, so that we can easily figure out what went wrong.

**Comment by polus-arcticus** [comment]
![image](https://github.com/CoopHive/coophive/assets/122753557/0b16a7dd-27bf-4efd-ac22-ac69df231676)

hey @gpylypchuk @mlegls i was checking out the inspect command and noticed we have private keys in plain text  being sent to the logs, let's definitely try to change this in the new logging paradigm

**Comment by mactus13** [comment]
Can be closed until we remove Solver and Mediator.
